Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.gui = "true"
    vb.customize [
      "modifyvm", :id, 
      "--nic1", "hostonly", 
      "--hostonlyadapter1", "vboxnet0",
      "--nicbootprio1", "1",
      "--boot1", "net",
      "--boot3", "none",
      "--boot2", "none",
      "--boot4", "none"
      ] 
  end
end