Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.customize [
      "modifyvm", :id, 
      "--nic1", "intnet",
      "--intnet1", "pxe_net",
      "--boot1", "net",
      "--boot2", "none",
      "--boot3", "none",
      "--boot4", "none"
    ] 
  end
end