Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |v|
    v.name = "foreman_master"
    v.memory = 2048
    v.cpus = 2
  end
end
